GET http://localhost:3001/posts

###

GET http://localhost:3001/posts/63cdf997aaad5da7ca865a38

###

GET http://localhost:3001/posts/asdf123asdf

###

POST https://mattsposts-api.onrender.com/posts
content-type: application/json

{
    "title": "sample",
    "description": "test",
    "username": "me",
    "user_id": 12345,
    "lastUpdated": "4:34PM"
}

### 

POST http://localhost:3001/posts
content-type: application/json

{
    "title": "d",
    "description": "k",
    "username": "pickemtt",
    "user_id": "google-oauth2|116384074292695553051"
}

###

DELETE http://localhost:3001/posts/640d1e134916eabbc7ce50e2

###

PATCH http://localhost:3001/posts/63cdf997aaad5da7ca865a38
content-type: application/json

{
    "title": "new title",
    "description": "new description",
    "username": "you",
    "user_id": 54321
}